resolver: lts-24.16

packages:
  - echoic

system-ghc: true
nix:
  enable: false
with-hpack: hpack

extra-deps:
  - github: NorfairKing/opt-env-conf
    commit: 32b5a2abef089e486c10fc09cd368d440b6a2aee
    subdirs:
      - opt-env-conf

  - github: NorfairKing/safe-coloured-text
    commit: 046f10147a058c00c2706d98c341219e3cbc7669
    subdirs:
      - safe-coloured-text
      - safe-coloured-text-layout
      - safe-coloured-text-terminfo

  - github: NorfairKing/autodocodec
    commit: 3dbe8d515c9fc0fe6313dfe92e9db1f4af4c50a3
    subdirs:
      - autodocodec
      - autodocodec-yaml

  - github: NorfairKing/cursor
    commit: 730bb65b21304e12fb712236d5a541c3774ed2ad
    subdirs:
      - cursor

  - github: NorfairKing/cursor-brick
    commit: 753454ed23f5fad216f4f1502b889a761dfb3a28
    subdirs:
      - cursor-brick
