name: echoic
version: 0.1.0.0
synopsis: Blind computing environment
description: Enable near-normal computing efficiency without vision.
license: AllRightsReserved
author: syd

dependencies:
  - base >= 4.17 && < 5

library:
  source-dirs: src
  dependencies:
    - brick
    - bytestring
    - mtl
    - opt-env-conf
    - path
    - text
    - typed-process >= 0.2
    - vty
    - vty-crossplatform

executables:
  echoic:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - echoic

ghc-options:
  - -Wall

default-extensions:
  - LambdaCase
  - OverloadedStrings
  - RecordWildCards
